# Generated by Django 4.1 on 2022-08-25 07:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='title', unique=True, verbose_name='URL'),
        ),
    ]
