# Generated by Django 4.1 on 2022-08-23 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Category')),
            ],
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-time_updated']},
        ),
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myblog.category'),
        ),
    ]
