# Generated by Django 4.1 on 2022-08-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_category_alter_topic_options_topic_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['category', '-time_updated'], 'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
    ]
